name: Publish snapshot to SciJava Maven

on: 
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: Publish snapshot
      run: ./gradlew publish
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    - uses: actions/upload-artifact@v4
      with:
        name: jar
        path: build/libs
        retention-days: 7
